## These two functions are intended to output the inverse of a matrix, while cacheing
## the inverse<if it is ever needed again the cache can be retrieved instead of
## having to recompute the inverse matrix.

## This function takes a matrix and makes a list with the original data, as well as 
## identifying information for cacheSolve to know weather it has been solved before
## and spaces to hold the cached data.

## NOTE: Be sure to input an invertible matrix

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinverse <- function(solve) i <<- solve
        getinverse <- function() i
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## This function takes the list generated by makeCacheMatrix and solves the matrix in it
## (i.e. gets its data and inverts it) and writes the output into the list. If called 
## again, it will output the previous result without recomputing.

cacheSolve <- function(x, ...) {
        i <- x$getinverse()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinverse(i)
        i
}
